name: nconf-yaml
version: 1.0.0
description: YAML format plugin for nconf
main: index.js
dependencies:
  js-yaml: '3.x >=3.2.3'
peerDependencies:
  nconf: '*'
repository:
  type: git
  url: "https://github.com/tellnes/nconf-yaml.git"
author: "Christian Tellnes <christian@tellnes.no> (http://christian.tellnes.com/)"
license: MIT
bugs:
  url: "https://github.com/tellnes/nconf-yaml/issues"
homepage: "https://github.com/tellnes/nconf-yaml"
publishConfig:
  registry: https://registry.npmjs.org/
