name: x-yaml
version: 1.0.0
description: JS-YAML with a friendly interface
main: index.js
dependencies:
  js-yaml: ^3.2.3
repository:
  type: git
  url: "https://github.com/rlidwka/x-yaml.git"
author: "Alex Kocharin <alex@kocharin.ru>"
license: MIT
bugs:
  url: "https://github.com/rlidwka/x-yaml/issues"
publishConfig:
  registry: https://registry.npmjs.org/
